apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: echo
          image: zerlok/otus-ma-k8s-python-echo:0.1.0
          ports:
            - containerPort: 8080
              name: service
