apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-echo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: echo.troshnev-otus-ma-k8s.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-app
                port:
                  number: 8000
